"""post table

Revision ID: ff2c4223ce4a
Revises: b0e2af0b55e3
Create Date: 2025-11-22 10:23:43.574638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff2c4223ce4a'
down_revision = 'b0e2af0b55e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=300), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('add_product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_add_product_product_name'))
        batch_op.drop_index(batch_op.f('ix_add_product_timestamp'))

    op.drop_table('add_product')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('add_product',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('product_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('product_description', sa.VARCHAR(length=256), nullable=True),
    sa.Column('available_stock', sa.INTEGER(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('add_product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_add_product_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_add_product_product_name'), ['product_name'], unique=False)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_timestamp'))

    op.drop_table('post')
    # ### end Alembic commands ###
